#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
service nginx restart
