#!/usr/bin/env bash
# Bash script to display numbers from 1 to 100 with Fizz, Buzz, and FizzBuzz conditions

# Using a for loop to iterate from 1 to 100

for ((i=1; i<=100; i++)); do
	#check if the number is a multiple of both 3 and 5
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo $i
	fi
done
