#!/usr/bin/env bash
# Bash script to tell a story based on /etc/passwd file

# Specify the path to the /etc/passwd file
passwd_file="/etc/passwd"

# Using a while loop to read lines from the file
while IFS=: read -r username _ uid gid info home shell; do
    # Display information about the user
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < "$passwd_file"
