#!/usr/bin/env bash
# Bash script to group visitors by IP and HTTP status code and display the data using awk

# Specify the path to the Apache log file
log_file="apache-access.log"

# Using awk to group by IP and HTTP status code, count occurrences, and display the data
awk '{ip_code_count[$1, $9]++} END {for (key in ip_code_count) print ip_code_count[key], key}' "$log_file" | sort -nr
