#!/usr/bin/env bash
# This script displays numbers and messages based on loop iteration

# Initializing a counter
count=1

while [ $count -le 20 ]; do
	case $count in
		4)
			echo -e "$count \nbad luck from china"
			;;
		9)
			echo -e "$count \nbad luck from japan"
			;;
		17)
			echo -e "$count \nbad luck from italy"
			;;
		*)
			echo $count
			;;
	esac

	((count++))
done
