#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

# Initialize variables

hour=0

while [ $hour -le 12 ]; do
	echo "Hour: $hour"

	minute=1

	while [ $minute -le 50 ]; do
		echo $minute
		((minute++))
	done

	((hour++))
done
