#!/usr/bin/env bash
# This script displays the content of the current directory in list format,
# showing only the part of the name after the first dash

# Using a for loop to iterate over files in the current directory
for file in *; do
	#check if the file is a regular file (not a directory and not hidden)
	if [ -f "$file" ] && [[ ! "$file" == .* ]]; then
		#extract part of name after -
		name=$(echo "$file" | cut -d'-' -f2-)
		#check if the extracted name is not empty before printing
		if [ -n "$name" ]; then
			echo "$name"
		fi
	fi
done
