#!/usr/bin/env bash
# web server to run nginx as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
root@ecdc65ecf5f7:/alx-system_engineering-devops/0x12-web_stack_debugging_2#
